New versions
git-svn-id: file:///home/simon/svn_repository/build@172 bfc3ebfc-e10d-0410-9382-de160f044a17

diff --git a/gnusound-0.7.4.diff b/gnusound-0.7.4.diff
--- a/gnusound-0.7.4.diff
+++ b/gnusound-0.7.4.diff
@@ -1,3 +1,58 @@
+--- gnusound-0.7.4/configure.orig	2005-07-06 10:57:07.000000000 +0100
++++ gnusound-0.7.4/configure	2007-06-02 21:26:07.000000000 +0100
+@@ -7935,9 +7935,9 @@
+ 
+ fi
+ if test $ac_cv_header_FLAC_format_h = yes; then
+-  echo "$as_me:$LINENO: checking for FLAC__file_decoder_new in -lFLAC" >&5
+-echo $ECHO_N "checking for FLAC__file_decoder_new in -lFLAC... $ECHO_C" >&6
+-if test "${ac_cv_lib_FLAC_FLAC__file_decoder_new+set}" = set; then
++  echo "$as_me:$LINENO: checking for FLAC__stream_decoder_new in -lFLAC" >&5
++echo $ECHO_N "checking for FLAC__stream_decoder_new in -lFLAC... $ECHO_C" >&6
++if test "${ac_cv_lib_FLAC_FLAC__stream_decoder_new+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+@@ -7955,11 +7955,11 @@
+ #endif
+ /* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+-char FLAC__file_decoder_new ();
++char FLAC__stream_decoder_new ();
+ int
+ main ()
+ {
+-FLAC__file_decoder_new ();
++FLAC__stream_decoder_new ();
+   ;
+   return 0;
+ }
+@@ -7986,20 +7986,20 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_lib_FLAC_FLAC__file_decoder_new=yes
++  ac_cv_lib_FLAC_FLAC__stream_decoder_new=yes
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
+-ac_cv_lib_FLAC_FLAC__file_decoder_new=no
++ac_cv_lib_FLAC_FLAC__stream_decoder_new=no
+ fi
+ rm -f conftest.err conftest.$ac_objext \
+       conftest$ac_exeext conftest.$ac_ext
+ LIBS=$ac_check_lib_save_LIBS
+ fi
+-echo "$as_me:$LINENO: result: $ac_cv_lib_FLAC_FLAC__file_decoder_new" >&5
+-echo "${ECHO_T}$ac_cv_lib_FLAC_FLAC__file_decoder_new" >&6
+-if test $ac_cv_lib_FLAC_FLAC__file_decoder_new = yes; then
++echo "$as_me:$LINENO: result: $ac_cv_lib_FLAC_FLAC__stream_decoder_new" >&5
++echo "${ECHO_T}$ac_cv_lib_FLAC_FLAC__stream_decoder_new" >&6
++if test $ac_cv_lib_FLAC_FLAC__stream_decoder_new = yes; then
+   cat >>confdefs.h <<\_ACEOF
+ #define HAVE_FLAC 1
+ _ACEOF
 --- gnusound-0.7.4/modules/file_ffmpeg.c.orig	2005-06-19 16:44:25.000000000 +0100
 +++ gnusound-0.7.4/modules/file_ffmpeg.c	2007-03-07 09:52:03.000000000 +0000
 @@ -77,7 +77,7 @@
