New versions
git-svn-id: file:///home/simon/svn_repository/build@2475 bfc3ebfc-e10d-0410-9382-de160f044a17

diff --git a/mjpegtools-1.9.0.diff b/mjpegtools-1.9.0.diff
--- a/mjpegtools-1.9.0.diff
+++ b/mjpegtools-1.9.0.diff
@@ -1,5 +1,17 @@
+--- mjpegtools-1.9.0/utils/videodev_mjpeg.h.orig	2001-08-28 17:45:44.000000000 +0100
++++ mjpegtools-1.9.0/utils/videodev_mjpeg.h	2015-02-15 17:12:39.391283617 +0000
+@@ -109,6 +109,9 @@
+ /*
+ Private IOCTL to set up for displaying MJPEG
+ */
++#ifndef BASE_VIDIOCPRIVATE
++#define BASE_VIDIOCPRIVATE    192
++#endif
+ #define MJPIOC_G_PARAMS       _IOR ('v', BASE_VIDIOCPRIVATE+0,  struct mjpeg_params)
+ #define MJPIOC_S_PARAMS       _IOWR('v', BASE_VIDIOCPRIVATE+1,  struct mjpeg_params)
+ #define MJPIOC_REQBUFS        _IOWR('v', BASE_VIDIOCPRIVATE+2,  struct mjpeg_requestbuffers)
 --- mjpegtools-1.9.0/mplex/lpcmstrm_in.cpp.orig	2005-10-13 17:43:10.000000000 +0100
-+++ mjpegtools-1.9.0/mplex/lpcmstrm_in.cpp	2010-06-15 22:13:17.000000000 +0100
++++ mjpegtools-1.9.0/mplex/lpcmstrm_in.cpp	2015-02-15 17:21:30.463244121 +0000
 @@ -53,7 +53,7 @@
  
  bool LPCMStream::Probe(IBitStream &bs )
@@ -9,3 +21,172 @@
      return 
          last_dot != NULL 
          && strcmp( last_dot+1, "lpcm") == 0;
+--- mjpegtools-1.9.0/lavtools/png2yuv.c.orig	2007-11-08 17:31:50.000000000 +0000
++++ mjpegtools-1.9.0/lavtools/png2yuv.c	2015-02-15 17:20:23.368249111 +0000
+@@ -242,7 +242,7 @@
+ 
+ void png_separation(png_structp png_ptr, png_row_infop row_info, png_bytep data)
+ {
+-  int row_nr = png_ptr->row_number; // internal variable ? 
++  int row_nr = png_get_current_row_number(png_ptr);
+   int i, width = row_info->width; 
+   int new_width = sh_param->new_width;
+ 
+@@ -402,7 +402,7 @@
+     }
+   png_read_end(png_ptr, info_ptr);
+ #endif  
+-  if (setjmp(png_ptr->jmpbuf)) {
++  if (setjmp(png_jmpbuf(png_ptr))) {
+     png_destroy_read_struct(&png_ptr, &info_ptr, &end_info);
+     return 2;
+     }
+--- mjpegtools-1.9.0/lavtools/liblavrec.c.orig	2006-05-18 16:50:42.000000000 +0100
++++ mjpegtools-1.9.0/lavtools/liblavrec.c	2015-02-15 17:08:41.350301321 +0000
+@@ -63,7 +63,7 @@
+  * errors here, check your linux/time.h && sys/time.h header setup.
+  */
+ #define _LINUX_TIME_H
+-#include <linux/videodev.h>
++#include <libv4l1-videodev.h>
+ #ifdef HAVE_SYS_SOUNDCARD_H
+ #include <sys/soundcard.h>
+ #endif
+--- mjpegtools-1.9.0/lavtools/testrec.c.orig	2004-07-29 21:26:00.000000000 +0100
++++ mjpegtools-1.9.0/lavtools/testrec.c	2015-02-15 17:14:33.557275127 +0000
+@@ -89,7 +89,7 @@
+  * errors here, check your linux/time.h && sys/time.h header setup.
+  */
+ #define _LINUX_TIME_H
+-#include <linux/videodev.h>
++#include <libv4l1-videodev.h>
+ #include <linux/soundcard.h>
+ 
+ /* These are explicit prototypes for the compiler, to prepare separation of audiolib.c */
+--- mjpegtools-1.9.0/lavtools/lavvideo.c.orig	2004-07-29 21:26:00.000000000 +0100
++++ mjpegtools-1.9.0/lavtools/lavvideo.c	2015-02-15 17:15:27.572271110 +0000
+@@ -63,7 +63,7 @@
+  * errors here, check your linux/time.h && sys/time.h header setup.
+  */
+ #define _LINUX_TIME_H
+-#include <linux/videodev.h>
++#include <libv4l1-videodev.h>
+ 
+ #include <videodev_mjpeg.h>
+ #include <frequencies.h>
+--- mjpegtools-1.9.0/lavtools/liblavplay.c.orig	2015-02-15 17:15:01.021273084 +0000
++++ mjpegtools-1.9.0/lavtools/liblavplay.c	2015-02-15 17:13:59.188277683 +0000
+@@ -68,7 +68,7 @@
+  * errors here, check your linux/time.h && sys/time.h header setup.
+  */
+ #define _LINUX_TIME_H
+-#include <linux/videodev.h>
++#include <libv4l1-videodev.h>
+ #else
+ #define VIDEO_MODE_PAL		0
+ #define VIDEO_MODE_NTSC		1
+--- mjpegtools-1.9.0/configure.orig	2009-01-06 06:49:27.000000000 +0000
++++ mjpegtools-1.9.0/configure	2015-02-15 17:06:58.845308944 +0000
+@@ -22636,8 +22636,8 @@
+ case $host in
+   *-*-linux*)
+   if test "${ac_cv_header_linux_videodev_h+set}" = set; then
+-  { echo "$as_me:$LINENO: checking for linux/videodev.h" >&5
+-echo $ECHO_N "checking for linux/videodev.h... $ECHO_C" >&6; }
++  { echo "$as_me:$LINENO: checking for libv4l1-videodev.h" >&5
++echo $ECHO_N "checking for libv4l1-videodev.h... $ECHO_C" >&6; }
+ if test "${ac_cv_header_linux_videodev_h+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ fi
+@@ -22645,8 +22645,8 @@
+ echo "${ECHO_T}$ac_cv_header_linux_videodev_h" >&6; }
+ else
+   # Is the header compilable?
+-{ echo "$as_me:$LINENO: checking linux/videodev.h usability" >&5
+-echo $ECHO_N "checking linux/videodev.h usability... $ECHO_C" >&6; }
++{ echo "$as_me:$LINENO: checking libv4l1-videodev.h usability" >&5
++echo $ECHO_N "checking libv4l1-videodev.h usability... $ECHO_C" >&6; }
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -22654,7 +22654,7 @@
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
+ $ac_includes_default
+-#include <linux/videodev.h>
++#include <libv4l1-videodev.h>
+ _ACEOF
+ rm -f conftest.$ac_objext
+ if { (ac_try="$ac_compile"
+@@ -22686,15 +22686,15 @@
+ echo "${ECHO_T}$ac_header_compiler" >&6; }
+ 
+ # Is the header present?
+-{ echo "$as_me:$LINENO: checking linux/videodev.h presence" >&5
+-echo $ECHO_N "checking linux/videodev.h presence... $ECHO_C" >&6; }
++{ echo "$as_me:$LINENO: checking libv4l1-videodev.h presence" >&5
++echo $ECHO_N "checking libv4l1-videodev.h presence... $ECHO_C" >&6; }
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+ cat confdefs.h >>conftest.$ac_ext
+ cat >>conftest.$ac_ext <<_ACEOF
+ /* end confdefs.h.  */
+-#include <linux/videodev.h>
++#include <libv4l1-videodev.h>
+ _ACEOF
+ if { (ac_try="$ac_cpp conftest.$ac_ext"
+ case "(($ac_try" in
+@@ -22727,25 +22727,25 @@
+ # So?  What about this header?
+ case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+   yes:no: )
+-    { echo "$as_me:$LINENO: WARNING: linux/videodev.h: accepted by the compiler, rejected by the preprocessor!" >&5
+-echo "$as_me: WARNING: linux/videodev.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: linux/videodev.h: proceeding with the compiler's result" >&5
+-echo "$as_me: WARNING: linux/videodev.h: proceeding with the compiler's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libv4l1-videodev.h: accepted by the compiler, rejected by the preprocessor!" >&5
++echo "$as_me: WARNING: libv4l1-videodev.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libv4l1-videodev.h: proceeding with the compiler's result" >&5
++echo "$as_me: WARNING: libv4l1-videodev.h: proceeding with the compiler's result" >&2;}
+     ac_header_preproc=yes
+     ;;
+   no:yes:* )
+-    { echo "$as_me:$LINENO: WARNING: linux/videodev.h: present but cannot be compiled" >&5
+-echo "$as_me: WARNING: linux/videodev.h: present but cannot be compiled" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: linux/videodev.h:     check for missing prerequisite headers?" >&5
+-echo "$as_me: WARNING: linux/videodev.h:     check for missing prerequisite headers?" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: linux/videodev.h: see the Autoconf documentation" >&5
+-echo "$as_me: WARNING: linux/videodev.h: see the Autoconf documentation" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: linux/videodev.h:     section \"Present But Cannot Be Compiled\"" >&5
+-echo "$as_me: WARNING: linux/videodev.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: linux/videodev.h: proceeding with the preprocessor's result" >&5
+-echo "$as_me: WARNING: linux/videodev.h: proceeding with the preprocessor's result" >&2;}
+-    { echo "$as_me:$LINENO: WARNING: linux/videodev.h: in the future, the compiler will take precedence" >&5
+-echo "$as_me: WARNING: linux/videodev.h: in the future, the compiler will take precedence" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libv4l1-videodev.h: present but cannot be compiled" >&5
++echo "$as_me: WARNING: libv4l1-videodev.h: present but cannot be compiled" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libv4l1-videodev.h:     check for missing prerequisite headers?" >&5
++echo "$as_me: WARNING: libv4l1-videodev.h:     check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libv4l1-videodev.h: see the Autoconf documentation" >&5
++echo "$as_me: WARNING: libv4l1-videodev.h: see the Autoconf documentation" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libv4l1-videodev.h:     section \"Present But Cannot Be Compiled\"" >&5
++echo "$as_me: WARNING: libv4l1-videodev.h:     section \"Present But Cannot Be Compiled\"" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libv4l1-videodev.h: proceeding with the preprocessor's result" >&5
++echo "$as_me: WARNING: libv4l1-videodev.h: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: libv4l1-videodev.h: in the future, the compiler will take precedence" >&5
++echo "$as_me: WARNING: libv4l1-videodev.h: in the future, the compiler will take precedence" >&2;}
+     ( cat <<\_ASBOX
+ ## ---------------------------------------------------- ##
+ ## Report this to mjpeg-developer@lists.sourceforge.net ##
+@@ -22754,8 +22754,8 @@
+      ) | sed "s/^/$as_me: WARNING:     /" >&2
+     ;;
+ esac
+-{ echo "$as_me:$LINENO: checking for linux/videodev.h" >&5
+-echo $ECHO_N "checking for linux/videodev.h... $ECHO_C" >&6; }
++{ echo "$as_me:$LINENO: checking for libv4l1-videodev.h" >&5
++echo $ECHO_N "checking for libv4l1-videodev.h... $ECHO_C" >&6; }
+ if test "${ac_cv_header_linux_videodev_h+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
